### ISSUE TITLE
Remaining Dependency on mistral-v2

### ISSUE THREAD

**Issue by ericreeves** [StackStorm-Exchange/stackstorm-aws_boto3#17]
The aws_boto3 pack is still using the mistral-v2 runner, which is no longer available in Stackstorm.

```
File "/opt/stackstorm/st2/lib/python3.6/site-packages/st2common/bootstrap/actionsregistrar.py", line 200, in _register_actions_from_pack
    raise ValueError(msg)

ValueError: Failed to register action "/opt/stackstorm/packs/aws_boto3/actions/create_vpc.yaml" from pack "aws_boto3": RunnerType mistral-v2 is not found. If you are using old and deprecated runner name, you need to switch to a new one. For more information, please see https://docs.stackstorm.com/upgrade_notes.html#st2-v0-9
```

**Comment by amanda11** [comment]
create_vpc and create_vpc_assume_role both use mistral-v2 and need converting to Orquesta.

**Comment by eric-al** [comment]
In case anybody else runs into this, for the time being you can just fork the repo, remove workflows/create_vpc.yaml and workflows/create_vpc_assume_role.yaml, and everything works like a champ.

**Comment by nmaludy** [comment]
@eric-al or @ericreeves would you be interested in making a PR to fix this?
