### ISSUE TITLE
Deployment CI task failing when tagging the releases 

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-aws_boto3#6]
We are seeing the following error when the (see [link](https://circleci.com/gh/StackStorm-Exchange/stackstorm-aws_boto3/20?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)) when CircleCI runs against the master branch.

```
Index updated.
Creating tag 0.3.0 for commit 1cd4f97824ccb8fddf7cff834408bf953a00c265
Pushing tag v0.3.0 to origin remote
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exited with code 128
```

**Comment by LindsayHill** [comment]
Should be fixed now. There's some change in behavior with CircleCI related to following projects & adding deploy keys, and sometimes it adds an extra key, which is read-only. Have deleted that key, and now it should use the correct read-write key.
